source 'https://rubygems.org'

ruby "2.1.5"
gem 'rails', '4.2.0'

gem 'mysql2'
gem 'sass-rails', '~> 5.0.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails', '~> 4.0.0'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc
gem 'kaminari'
gem 'counter_culture'
gem 'carrierwave'
gem 'fog'
gem 'unf'
gem 'rails_autolink'
gem 'twitter'
gem 'fb_graph'
gem 'haml-rails'
gem 'activerecord-import'
gem 'acts-as-taggable-on'
gem 'colored'
gem 'unicorn'
gem "font-awesome-rails"

gem "seed-fu"
gem 'devise'
gem 'omniauth'
gem 'omniauth-facebook'

group :development do
  gem 'letter_opener'
  gem 'view_source_map'

  # deploy
  gem 'capistrano', '~> 3.2.1'
  gem 'capistrano-rails'
  gem 'capistrano-rbenv'
  gem 'capistrano-bundler'
  gem 'capistrano3-unicorn'
end

group :development, :test do
  gem 'byebug'
  gem 'web-console', '~> 2.0.0'
  gem 'spring'
  gem 'faker'
  gem 'rspec-rails', '~> 3.0.1'
  gem 'rspec-mocks'
  gem 'rspec-activemodel-mocks'
  gem 'factory_girl_rails'
  gem 'database_rewinder'
  gem 'dotenv-rails', :groups => [:development, :test]
  gem 'capybara'
end

group :test do
  gem 'fuubar'
  gem 'rspec-instafail'
  gem 'test_after_commit'
  gem 'webmock'
end
